
Style/ClassCheck:
  EnforcedStyle: kind_of?

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BracesAroundHashParameters:
  Enabled: false

Lint/UselessAssignment:
  Exclude:
    - '**/spec/**/*'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/IndentHash:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: exploded

Style/DoubleNegation:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: false

# Needed for $verbose
Style/GlobalVars:
  Enabled: false

Style/FileName:
  Enabled: false

# $? Exit
Style/SpecialGlobalVars:
  Enabled: false

Metrics/AbcSize:
  Max: 63
  Exclude:
    - '**/lib/*/options.rb'

# Both string notations are okay
Style/StringLiterals:
  Enabled: false

# The %w might be confusing for new users
Style/WordArray:
  MinSize: 19

# Not a good thing
Style/RedundantSelf:
  Enabled: false

# raise and fail are both okay
Style/SignalException:
  Enabled: false

# Better too much 'return' than one missing
Style/RedundantReturn:
  Enabled: false

# Having if in the same line might not always be good
Style/IfUnlessModifier:
  Enabled: false

# That looks wrong
Style/AlignHash:
  Enabled: false

# and and or is okay
Style/AndOr:
  Enabled: false

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 320

Metrics/CyclomaticComplexity:
  Max: 17

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 370

# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 17

Metrics/PerceivedComplexity:
  Max: 18

Style/DotPosition:
  Enabled: false

Style/GuardClause:
  Enabled: false



# Split


# e.g. 
# def self.is_supported?(platform)
# we may never use `platform`
Lint/UnusedMethodArgument:
  Enabled: false

# the let(:key) { ... }
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - '**/spec/**/*'

# We use `is_supported?` everywhere already
Style/PredicateName:
  Enabled: false

# Disable '+ should be surrounded with a single space' for xcodebuild_spec.rb
Style/SpaceAroundOperators:
  Exclude:
    - '**/spec/actions_specs/xcodebuild_spec.rb'

Metrics/MethodLength:
  Exclude:
    - '**/lib/fastlane/actions/*.rb'
    - '**/bin/fastlane'
    - '**/lib/*/options.rb'
  Max: 60

AllCops:
  Include:
    - '**/fastlane/Fastfile'
  Exclude:
    - '**/lib/assets/custom_action_template.rb'

##################
# TODO
##################

# Offense count: 7
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 320

# Offense count: 4
Metrics/CyclomaticComplexity:
  Max: 17

# Offense count: 489
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 372

# Offense count: 5
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 17

# Offense count: 3
Metrics/PerceivedComplexity:
  Max: 18

# Offense count: 1
# Cop supports --auto-correct.
Style/Alias:
  Enabled: false

# Offense count: 14
# Cop supports --auto-correct.
# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
Style/AlignHash:
  Enabled: false

# Offense count: 22
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  Enabled: false

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 19
Style/Documentation:
  Enabled: false

# Offense count: 112
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/DotPosition:
  Enabled: false

# Offense count: 12
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundClassBody:
  Enabled: false

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Offense count: 74
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MultilineOperationIndentation:
  Enabled: false

# Offense count: 10
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 14

# Offense count: 2
# Cop supports --auto-correct.
Style/PerlBackrefs:
  Enabled: false

# Offense count: 19
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: false

# Offense count: 77
# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false

# Offense count: 38
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: false

# Offense count: 291
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Enabled: false

# Offense count: 881
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
Style/WordArray:
  MinSize: 19
